version: '3'

tasks:
  default:
    cmds:
      - task: replace-repository-name
      - task: replace-image-name
      - task: enable-dependabot
      - task: remove-setup-workflow

  # replace repository name references
  replace-repository-name:
    cmds:
      - sed -i 's|docker-package|{{.REPOSITORY_NAME}}|g' README.md package.json mkdocs.yml
      - mv {docker-package,{{.REPOSITORY_NAME}}}.code-workspace

  # replace image name references
  replace-image-name:
    cmds:
      - sed -i 's|package|{{.IMAGE_NAME}}|g' README.md

  # enable dependabot
  enable-dependabot:
    cmds:
      - mv .github/dependabot.yml{.disabled,}

  # remove setup workflow
  remove-setup-workflow:
    cmds:
      - rm .github/workflows/setup.yml
